'use client'

import { useEffect, useRef } from 'react'
import { useTelemetry } from './TelemetryProvider'

/**
 * Embeds the real dashboard HUD in an iframe, feeding it telemetry
 * data via postMessage. The dashboard-embed.html is generated by
 * `scripts/build-web-demo.mjs` from the actual dashboard source.
 *
 * The demo CSS makes the dashboard panels flex-grow to fill whatever
 * width the iframe is, so no transform scaling is needed — the iframe
 * is simply 100% of the container.
 */
export function DashboardEmbed() {
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const { data, status } = useTelemetry()

  // ── Post telemetry data to iframe on every update ──
  useEffect(() => {
    const iframe = iframeRef.current
    if (!iframe?.contentWindow || !data) return
    iframe.contentWindow.postMessage(
      { type: 'k10-telemetry', snapshot: data },
      '*',
    )
  }, [data])

  return (
    <div className="flex flex-col gap-3">
      <span className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)]">
        Live Dashboard Demo
      </span>

      {/* Dashboard iframe — fills container, panels flex to fit */}
      <div
        className="relative rounded-xl overflow-hidden border border-[var(--border-subtle)]"
        style={{ background: '#000', aspectRatio: '16 / 5' }}
      >
        {status !== 'live' && (
          <div className="absolute inset-0 flex items-center justify-center z-10" style={{ background: '#000' }}>
            <span className="text-sm text-[var(--text-dim)] animate-pulse">
              Connecting to telemetry...
            </span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src="/_demo/dashboard-embed.html"
          title="K10 Motorsports Dashboard Demo"
          className="border-0 w-full h-full"
          sandbox="allow-scripts allow-same-origin"
          style={{
            background: '#000',
            opacity: status === 'live' ? 1 : 0,
            transition: 'opacity 0.5s ease',
          }}
        />
      </div>
    </div>
  )
}
